apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        environment: development
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: app-ng
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
      - name: user-service
        image: ${ECR_REGISTRY}/${ECR_PREFIX}/user-service:${IMAGE_TAG}
        ports:
        - containerPort: 8014
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        - name: DEPLOYMENT_STRATEGY
          value: "${DEPLOYMENT_STRATEGY}"
        - name: IMAGE_TAG
          value: "${IMAGE_TAG}"
        - name: SPRING_DATASOURCE_URL
          value: "${DB_URL}"
        - name: SPRING_DATASOURCE_USERNAME
          value: "${DB_USERNAME}"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "${DB_PASSWORD}"
        - name: JWT_SECRET
          value: "${JWT_SECRET}"
        - name: JWT_REFRESH_SECRET
          value: "${JWT_REFRESH_SECRET}"
        - name: SPRING_REDIS_HOST
          value: "${REDIS_HOST}"
        - name: SPRING_REDIS_PORT
          value: "${REDIS_PORT}"
        - name: SPRING_MAIL_USERNAME
          value: "${MAIL_USERNAME}"
        - name: SPRING_MAIL_PASSWORD
          value: "${MAIL_PASSWORD}"
        - name: GOOGLE_CLIENT_ID
          value: "${GOOGLE_CLIENT_ID}"
        - name: GOOGLE_CLIENT_SECRET_ID
          value: "${GOOGLE_CLIENT_SECRET_ID}"
        - name: USER_SERVICE_PASSPORT_SECRET
          value: "${USER_SERVICE_PASSPORT_SECRET}"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery-service:8761/eureka"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
