# Stable Service
apiVersion: v1
kind: Service
metadata:
  name: user-service-stable
  namespace: app
  labels:
    app: user
    service: user-service
    version: stable
spec:
  selector:
    app: user
    service: user-service
  ports:
    - port: 8014
      targetPort: 8014
      protocol: TCP
      name: http
  type: ClusterIP

---
# Canary Service
apiVersion: v1
kind: Service
metadata:
  name: user-service-canary
  namespace: app
  labels:
    app: user
    service: user-service
    version: canary
spec:
  selector:
    app: user
    service: user-service
  ports:
    - port: 8014
      targetPort: 8014
      protocol: TCP
      name: http
  type: ClusterIP

---
# Main Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: app
  labels:
    app: user
    service: user-service
spec:
  selector:
    app: user
    service: user-service
  ports:
    - port: 8014
      targetPort: 8014
      protocol: TCP
      name: http
  type: ClusterIP