apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '5'
    alb.ingress.kubernetes.io/group.name: app-ingress
    alb.ingress.kubernetes.io/group.order: '1'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          # Auth Service
          - backend:
              service:
                name: auth-service-stable
                port:
                  number: 80
            path: /auth
            pathType: Prefix
          - backend:
              service:
                name: auth-service-canary
                port:
                  number: 80
            path: /auth
            pathType: Prefix
          # User Service
          - backend:
              service:
                name: user-service-stable
                port:
                  number: 80
            path: /users
            pathType: Prefix
          - backend:
              service:
                name: user-service-canary
                port:
                  number: 80
            path: /users
            pathType: Prefix