# Stable Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service-stable
  namespace: app
  labels:
    app: auth
    service: auth-service
    version: stable
spec:
  selector:
    app: auth
    service: auth-service
  ports:
    - port: 80          # Ingress에서 참조하는 포트
      targetPort: 8015  # 실제 Pod 포트
      protocol: TCP
      name: http
  type: ClusterIP

---
# Canary Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service-canary
  namespace: app
  labels:
    app: auth
    service: auth-service
    version: canary
spec:
  selector:
    app: auth
    service: auth-service
  ports:
    - port: 80          # Ingress에서 참조하는 포트
      targetPort: 8015  # 실제 Pod 포트
      protocol: TCP
      name: http
  type: ClusterIP

---
# Main Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app
  labels:
    app: auth
    service: auth-service
spec:
  selector:
    app: auth
    service: auth-service
  ports:
    - port: 80          # Ingress에서 참조하는 포트
      targetPort: 8015  # 실제 Pod 포트
      protocol: TCP
      name: http
  type: ClusterIP